/**:
  ros__parameters:
    apple_pluck_impedance_control_displacement:
      update_rate: 200
      base_frame: lbr_link_0
      ee_frame: lbr_link_ee
      cartesian_axis: z
      cartesian_displacement_threshold_m: 0.1
      state_topic: lbr_state
      command_topic: kuka_clik_controller/target_frame
      wrench_topic: force_torque_broadcaster/wrench
      force_release_threshold_newton: 5.0
      force_release_duration_sec: 3.0
      force_release_shutdown_delay_sec: 0.8
      debug_log_enabled: false
      debug_log_rate_hz: 2.0
      subscriber_latch_delay_sec: 1.0
    move_to_start:
      update_rate: 200
      target_joint_position:
      - 0
      - 10
      - 0
      - -80
      - 0
      - 90
      - 0
      joint_move_tolerance: 0.01
      move_to_pos_v_max:
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      move_to_pos_a_max: 2.0
      move_to_pos_j_max: 5.0
      start_action_needed: false
      subscriber_latch_delay_sec: 1.0
      debug_log_enabled: false
      debug_log_rate_hz: 2.0
    move_to_start_recover:
      update_rate: 200
      target_joint_position:
      - 0
      - 10
      - 0
      - -80
      - 0
      - 90
      - 0
      joint_move_tolerance: 0.15
      move_to_pos_v_max:
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      - 40.0
      move_to_pos_a_max: 2.0
      move_to_pos_j_max: 5.0
      start_action_needed: true
      wait_for_physical_arrival: true
      subscriber_latch_delay_sec: 1.0
      debug_log_enabled: false
      debug_log_rate_hz: 2.0
    audio_cue_play:
      frequency_hz: 1500
      duration_ms: 1500
    audio_cue_snap:
      frequency_hz: 2000
      duration_ms: 500
