kuka_clik_controller:
  ros__parameters:
    update_rate: 1000
    robot_base_link: "lbr_link_0"
    end_effector_link: "lbr_link_ee"
    compliance_ref_link: "lbr_link_ee"
    joints:
      - lbr_A1
      - lbr_A2
      - lbr_A3
      - lbr_A4
      - lbr_A5
      - lbr_A6
      - lbr_A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    max_linear_velocity: 0.2
    max_angular_velocity: 0.2
    clik_dt: 0.001
    clik_it_max: 100
    clik_eps: 1e-4
    clik_filter_alpha: 0.99

cartesian_impedance_controller:
  ros__parameters:
    update_rate: 1000
    robot_base_link: "lbr_link_0"
    end_effector_link: "lbr_link_ee"
    compliance_ref_link: "lbr_link_ee"
    ft_sensor_ref_link: "lbr_link_ee"
    compensate_gravity: false
    compensate_coriolis: false
    delta_tau_max: 1.0
    joints:
      - lbr_A1
      - lbr_A2
      - lbr_A3
      - lbr_A4
      - lbr_A5
      - lbr_A6
      - lbr_A7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    command_current_configuration: false
    stiffness:
      trans_x: 200.0
      trans_y: 200.0
      trans_z: 200.0
      rot_x: 20.0
      rot_y: 20.0
      rot_z: 20.0
    nullspace_stiffness: 0.5
    nullspace_desired_configuration: [0.0, 0.5233, 0.0, -0.7853, 0.0, 1.5707, 0.0]
    compensate_dJdq: false